### ISSUE TITLE
Customize the base path

### ISSUE THREAD

**Issue by NemoAlex** [mikenorthorp/gulp-shopify-upload#1]
I saw the comment:

```
* The original path to a file may be something like shop/assets/site.css
* whereas we require assets/site.css in the API. To customize the base
* set shopify.options.base config option.
```

But still don't understand where to set `shopify.options.base`

**Comment by mikenorthorp** [comment]
Sorry I think I removed that and didn't update the readme. For now just make sure the gulpfile is in the directory above the assets directory.

**Comment by NemoAlex** [comment]
Thanks for the reply.
But it is a nice feature and I really need it.In my project, the gulpfile isn't in the theme dir. There are some other steps before upload to shopify server. These steps require some files in other dirs. So the gulpfile is in the root of the project but the theme is one of the dirs in root.

It would be very nice if you add the feature back, in any ways.

Thanks again for the great work you have done here.
