### ISSUE TITLE
Upload and download task

### ISSUE THREAD

**Issue by mrself** [mikenorthorp/gulp-shopify-upload#16]
It will be great to have upload and download task. Or they exist?

**Comment by mikenorthorp** [comment]
No download task, this plugin is meant to do one thing, watch your folder
and upload theme files to shopify.

**Comment by mrself** [comment]
grunt-shopify wins

**Comment by mikenorthorp** [comment]
Grunt is more suited to task based stuff. Gulp is streaming based. If you
want tasks and the like, use grunt. Gulp is used in streaming workflows a
lot better than grunt is. This plugin is actually modified from the
Grunt-shopify project to work with Gulp.

**Comment by mrself** [comment]
I know it. Yesterday I installed your plugin and tried to download theme with it. It was suprising when I discovered that plugin could not do it :) but i think i will go to this plugin soon.
