### ISSUE TITLE
Prod push?

### ISSUE THREAD

**Issue by yayromina** [mikenorthorp/gulp-shopify-upload#19]
I have a dev shop and a production shop, each with their own API key etc.  It would be cool to have two tasks- one for watching -> upload as I develop, and one for when I'm ready to push my whole branch to production.

I tried writing a new task that only returned the gulpShopify function but that didn't work.  Is this something that may be supported in the future?  Otherwise, I guess I could toggle comments between which environment I want to upload to, and just touch all affected files.. seems tedious though.

**Comment by joeldrapper** [comment]
Hey @yayromina, this PR #11 should make this possible. It's likely to be merged soon I think.
