### ISSUE TITLE
Hit stream high water mark of 16 files while uploading

### ISSUE THREAD

**Issue by Soviut** [mikenorthorp/gulp-shopify-upload#21]
Because gulp-shopify-upload doesn't act as a stream terminus and because it was the only step in my pipeline (no `gulp.dest()`), I managed to hit the stream high water mark of 16 files while uploading.

I solved this by using https://github.com/Floby/node-stream-sink at the end of my pipeline as follows:

``` coffeescript
sink = require 'stream-sink'

gulp.src "#{dest.env}/**/*"
    .pipe gulpShopify shopifyConfig.api_key, shopifyConfig.password, shopifyConfig.url, shopifyConfig.theme_id, options
    .pipe sink()
```

It might be a good idea to document this for doing mass uploads, as opposed to live watching.

**Comment by mikenorthorp** [comment]
This might have been fixed in the latest 2.0.0 release, it now supports mass uploads, let me know if there are still issues with your scenario.
