### ISSUE TITLE
Getting ready message but no upload

### ISSUE THREAD

**Issue by dan-gamble** [mikenorthorp/gulp-shopify-upload#7]
Hey,

I'm getting the ready message after editing a file, 'Ready to upload too shop.myshopify.com/' but then after that nothing happens it seems the `stream` isn't being build in the `index.js` file. The code i have is: https://gist.github.com/DanGamble89/5fc93960a1d190937f64

Any ideas as to why it's not uploading?

**Comment by mikenorthorp** [comment]
Helped you fix it by following the readme :D

**Comment by dan-gamble** [comment]
I have no idea what fixed it but your help in the Slack definitely went towards fixing it :D
