### ISSUE TITLE
Callback after every file is uploaded

### ISSUE THREAD

**Issue by clementoriol** [mikenorthorp/gulp-shopify-upload#8]
Hi ! Thanks for the plugin, it's currently working very well for me.
However, I'm having issue reloading the page once every file is uploaded.

I'm trying to chain tasks, and gulp seems to have some issue with knowing when the gulpShopify uploads are done. It seems to trigger the task end too early.

Is there any kind of callback implemented in your plugin ? Or do you have any idea how it could be accomplished ?

Thank you

**Comment by mikenorthorp** [comment]
We use browsersync with a slight delay since we currently dont have any way
to know when its finished uploading. This refreshes the page when assets
are uploaded.

**Comment by pushred** [comment]
Why not defer the through2 callback until `shopify.upload` returns it's own? shopify-api doesn't callback for the asset PUT method [until a response is received](https://github.com/ctalkington/node-shopify-api/blob/master/lib/resource.js#L165). Seems to work for me like this:

``` js
browserSync.init({
  proxy: config.store
});

watch('.build')
  .pipe(shopify(config.api_key, config.password, config.store, config.theme_id, { basePath: '.build' }))
  .pipe(browserSync.stream());
```

See diff: https://github.com/mikenorthorp/gulp-shopify-upload/compare/master...pushred:upload-callback
